import {
  Home,
  MessageSquare,
  Printer,
  ShoppingBag,
  Zap,
} from "lucide-react"
import type { LaserMaterial, Product } from "@/lib/dripforge/types"
import { PRODUCT_MODEL_URLS } from "@/lib/dripforge/product-model-defaults"

export const navItems = [
  { id: "home", label: "Home", icon: Home },
  { id: "3d-druck", label: "3D-Druck", icon: Printer },
  { id: "laser", label: "Laser & Cut", icon: Zap },
  { id: "shop", label: "Shop", icon: ShoppingBag },
  { id: "kontakt", label: "Kontakt", icon: MessageSquare },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Geometrischer Handyhalter",
    description:
      "Modernes geometrisches Design. Perfekt fuer Schreibtisch oder Nachttisch.",
    price: 19.99,
    originalPrice: 24.99,
    basisPreis: 24.99,
    saleRabattTyp: "percent",
    saleRabattWert: 20,
    type: "3d",
    sale: true,
    modelUrl: PRODUCT_MODEL_URLS["1"],
    dimensionsMm: { length: 85, width: 72, height: 45 },
    volumen: 45.2,
    gewicht: 58,
  },
  {
    id: "2",
    name: "Desktop Kabelhalter",
    description:
      "Halten Sie Ihre Kabel ordentlich mit dieser eleganten Kabelmanagement-Loesung.",
    price: 19.99,
    originalPrice: null,
    type: "3d",
    sale: false,
    modelUrl: PRODUCT_MODEL_URLS["2"],
    dimensionsMm: { length: 42, width: 28, height: 18 },
    volumen: 12.8,
    gewicht: 22,
  },
  {
    id: "3",
    name: "Kopfhoererhalter",
    description:
      "Platzsparender Kopfhoererhalter fuer unter den Schreibtisch.",
    price: 14.99,
    originalPrice: null,
    type: "3d",
    sale: false,
    modelUrl: PRODUCT_MODEL_URLS["3"],
    dimensionsMm: { length: 120, width: 95, height: 35 },
    volumen: 68.5,
    gewicht: 95,
  },
  {
    id: "4",
    name: "Sukkulenten Pflanztopf",
    description: "Minimalistischer Pflanztopf mit Drainage fuer kleine Pflanzen.",
    price: 29.99,
    originalPrice: null,
    type: "3d",
    sale: false,
    modelUrl: PRODUCT_MODEL_URLS["4"],
    dimensionsMm: { length: 95, width: 95, height: 110 },
    volumen: 120.4,
    gewicht: 142,
  },
  {
    id: "5",
    name: "Holz Untersetzer Set",
    description:
      "Set aus 4 Premium Holzuntersetzern mit Ihrem individuellen Design.",
    price: 24.99,
    originalPrice: 34.99,
    type: "laser",
    sale: true,
    laserMaterialId: "wood",
    varianten: [],
  },
  {
    id: "6",
    name: "LED Acryl Schild",
    description:
      "Beleuchtetes Acrylschild mit individuellem Text oder Logo. Inkl. LED-Sockel.",
    price: 49.99,
    originalPrice: null,
    type: "laser",
    sale: false,
    laserMaterialId: "acrylic",
    varianten: ["Weiss opal", "Schwarz matt", "Rot transparent"],
  },
  {
    id: "7",
    name: "Leder Schlüsselanhänger",
    description: "Echter Lederschlüsselanhänger mit individueller Textgravur.",
    price: 9.99,
    originalPrice: 12.99,
    type: "laser",
    sale: true,
    laserMaterialId: "leather",
    varianten: ["Echtleder Braun", "Echtleder Schwarz"],
  },
  {
    id: "8",
    name: "Schiefer Namensschild",
    description:
      "Elegantes Schieferschild perfekt fuer Auszeichnungen oder Deko.",
    price: 39.99,
    originalPrice: null,
    type: "laser",
    sale: false,
    laserMaterialId: "stone",
    varianten: [],
  },
]

// Material data for 3D printing
export const materials3D = [
  {
    id: "pla",
    name: "PLA",
    fullName: "Polylactid",
    description: "Umweltfreundliches, biologisch abbaubares Material, perfekt für Prototypen, Dekoartikel und Anwendungen mit geringer Belastung.",
    strength: 60,
    flexibility: 30,
    heatResistance: 40,
    easeOfUse: 95,
    advantages: ["Biologisch abbaubar & umweltfreundlich", "Kein beheiztes Bett erforderlich", "Geringer Verzug", "Grosse Farbauswahl", "Lebensmittelechte Optionen verfügbar"],
    considerations: ["Geringe Hitzebeständigkeit (~60°C)", "Spröde unter Belastung", "Nicht für Aussenbereich geeignet"],
    bestFor: ["Prototypen", "Dekoartikel", "Figuren", "Lernmodelle", "Niedriglast-Teile"],
    colors: [
      { id: "pla-weiss", name: "Weiss", hex: "#FFFFFF", inStock: true, image: "/filaments/pla-weiss.png", printedExample: "/filaments/printed-pla-weiss.png" },
      { id: "pla-schwarz", name: "Schwarz", hex: "#1a1a1a", inStock: true, image: "/filaments/pla-schwarz.png", printedExample: "/filaments/printed-pla-schwarz.png" },
      { id: "pla-rot", name: "Rot", hex: "#DC2626", inStock: true, image: "/filaments/pla-rot.png", printedExample: "/filaments/printed-pla-rot.png" },
      { id: "pla-blau", name: "Blau", hex: "#2563EB", inStock: true, image: "/filaments/pla-blau.png", printedExample: "/filaments/printed-pla-blau.png" },
      { id: "pla-gruen", name: "Grün", hex: "#16A34A", inStock: true, image: "/filaments/pla-gruen.png", printedExample: "/filaments/printed-pla-gruen.png" },
      { id: "pla-gelb", name: "Gelb", hex: "#EAB308", inStock: true, image: "/filaments/pla-gelb.png", printedExample: "/filaments/printed-pla-gelb.png" },
      { id: "pla-orange", name: "Orange", hex: "#EA580C", inStock: true, image: "/filaments/pla-orange.png", printedExample: "/filaments/printed-pla-orange.png" },
      { id: "pla-pink", name: "Pink", hex: "#EC4899", inStock: false, image: null, printedExample: null },
      { id: "pla-grau", name: "Grau", hex: "#6B7280", inStock: true, image: "/filaments/pla-grau.png", printedExample: "/filaments/printed-pla-grau.png" },
      { id: "pla-silber", name: "Silber", hex: "#A8A29E", inStock: true, image: "/filaments/pla-silber.png", printedExample: "/filaments/printed-pla-silber.png" },
      { id: "pla-gold", name: "Gold", hex: "#D97706", inStock: false, image: null, printedExample: null },
      { id: "pla-transparent", name: "Transparent", hex: "#E5E7EB", inStock: true, image: "/filaments/pla-transparent.png", printedExample: "/filaments/printed-pla-transparent.png" },
    ],
  },
  {
    id: "petg",
    name: "PETG",
    fullName: "Polyethylenterephthalat-Glykol",
    description: "Ausgezeichnete Balance zwischen Festigkeit und Flexibilität. Ideal für funktionale Teile und Aussenanwendungen.",
    strength: 75,
    flexibility: 50,
    heatResistance: 70,
    easeOfUse: 80,
    advantages: ["Hervorragende Schlagfestigkeit", "UV-beständig", "Chemikalienbeständig", "Lebensmittelecht", "Gute Schichthaftung"],
    considerations: ["Neigt zu Fädenziehen", "Erfordert höhere Temperaturen", "Kann bei Feuchtigkeit Probleme machen"],
    bestFor: ["Funktionale Teile", "Aussenanwendungen", "Mechanische Komponenten", "Wasserdichte Drucke", "Lebensmittelbehälter"],
    colors: [
      { id: "petg-weiss", name: "Weiss", hex: "#FFFFFF", inStock: true, image: "/filaments/petg-weiss.png", printedExample: "/filaments/printed-petg-weiss.png" },
      { id: "petg-schwarz", name: "Schwarz", hex: "#1a1a1a", inStock: true, image: "/filaments/petg-schwarz.png", printedExample: "/filaments/printed-petg-schwarz.png" },
      { id: "petg-transparent", name: "Transparent", hex: "#E5E7EB", inStock: true, image: "/filaments/petg-transparent.png", printedExample: "/filaments/printed-petg-transparent.png" },
      { id: "petg-blau", name: "Blau", hex: "#3B82F6", inStock: true, image: "/filaments/petg-blau.png", printedExample: "/filaments/printed-petg-blau.png" },
      { id: "petg-rot", name: "Rot", hex: "#EF4444", inStock: false, image: null, printedExample: null },
      { id: "petg-gruen", name: "Grün", hex: "#22C55E", inStock: true, image: "/filaments/petg-gruen.png", printedExample: "/filaments/printed-petg-gruen.png" },
      { id: "petg-orange", name: "Orange", hex: "#F97316", inStock: true, image: "/filaments/petg-orange.png", printedExample: "/filaments/printed-petg-orange.png" },
      { id: "petg-grau", name: "Grau", hex: "#9CA3AF", inStock: true, image: "/filaments/petg-grau.png", printedExample: "/filaments/printed-petg-grau.png" },
    ],
  },
  {
    id: "asa",
    name: "ASA",
    fullName: "Acrylnitril-Styrol-Acrylat",
    description: "Premium-Material für professionelle Anwendungen mit aussergewöhnlicher UV- und Wetterbeständigkeit.",
    strength: 85,
    flexibility: 40,
    heatResistance: 85,
    easeOfUse: 60,
    advantages: ["Hervorragende UV-Beständigkeit", "Hohe Hitzetoleranz", "Professionelle Oberfläche", "Langlebig im Aussenbereich", "Behält Farbe bei"],
    considerations: ["Erfordert geschlossenen Druckraum", "Höherer Preis", "Kann ausgasen"],
    bestFor: ["Aussenteile", "Automotive-Komponenten", "Professionelle Prototypen", "Langzeit-Exponate", "Industrielle Anwendungen"],
    colors: [
      { id: "asa-weiss", name: "Weiss", hex: "#F5F5F4", inStock: true, image: "/filaments/asa-weiss.png", printedExample: "/filaments/printed-asa-weiss.png" },
      { id: "asa-schwarz", name: "Schwarz", hex: "#171717", inStock: true, image: "/filaments/asa-schwarz.png", printedExample: "/filaments/printed-asa-schwarz.png" },
      { id: "asa-grau", name: "Grau", hex: "#737373", inStock: true, image: "/filaments/asa-grau.png", printedExample: "/filaments/printed-asa-grau.png" },
      { id: "asa-beige", name: "Beige", hex: "#D6D3D1", inStock: true, image: "/filaments/asa-beige.png", printedExample: "/filaments/printed-asa-beige.png" },
      { id: "asa-blau", name: "Blau", hex: "#1D4ED8", inStock: false, image: null, printedExample: null },
    ],
  },
]

// Laser materials
export const laserMaterials: LaserMaterial[] = [
  {
    id: "wood",
    name: "Holz",
    icon: "🪵",
    iconBg: "bg-orange-500/20",
    iconColor: "text-orange-400",
    description: "Natürliche Wärme und klassische Ausstrahlung. Perfekt für Schilder, Geschenke und dekorative Stücke.",
    types: ["Sperrholz", "MDF", "Bambus", "Hartholz", "Kork"],
    canEngrave: true,
    canCut: true,
    maxThickness: "12mm",
    applications: ["Individuelle Schilder", "Untersetzer", "Schmuck", "Namensschilder", "Wandkunst", "Schlüsselanhänger"],
  },
  {
    id: "acrylic",
    name: "Acryl",
    icon: "◻️",
    iconBg: "bg-cyan-500/20",
    iconColor: "text-cyan-400",
    description: "Elegante, moderne Oberfläche mit lebhaften Farben. Ideal für Beschilderung und zeitgenössische Designs.",
    types: ["Klar", "Matt", "Farbig", "Spiegel", "Fluoreszierend"],
    canEngrave: true,
    canCut: true,
    maxThickness: "10mm",
    applications: ["LED-Schilder", "Displays", "Auszeichnungen", "Schmuck", "Schlüsselanhänger", "Dekorationen"],
  },
  {
    id: "stone",
    name: "Schiefer & Stein",
    icon: "🗻",
    iconBg: "bg-slate-500/20",
    iconColor: "text-slate-400",
    description: "Eleganter Naturstein mit permanenter Gravur. Perfekt für Premium-Geschenke und Gedenktafeln.",
    types: ["Naturschiefer", "Marmor", "Granit"],
    canEngrave: true,
    canCut: false,
    maxThickness: null,
    applications: ["Untersetzer", "Käsebretter", "Hausschilder", "Gedenktafeln", "Auszeichnungen"],
  },
  {
    id: "leather",
    name: "Leder",
    icon: "👜",
    iconBg: "bg-amber-500/20",
    iconColor: "text-amber-400",
    description: "Klassische Textur mit personalisierten Gravuren. Ideal für Accessoires und individuelle Artikel.",
    types: ["Echtleder", "Veganes Leder", "Wildleder", "Kunstleder"],
    canEngrave: true,
    canCut: true,
    maxThickness: "5mm",
    applications: ["Geldbörsen", "Gürtel", "Schlüsselanhänger", "Lesezeichen", "Patches", "Taschen"],
  },
]

// Process steps
export const processSteps = [
  { number: 1, title: "Design & Upload", description: "Laden Sie Ihr 3D-Modell (STL, OBJ) hoch oder beschreiben Sie Ihre Idee. Unser System analysiert Dimensionen und Komplexität." },
  { number: 2, title: "Materialauswahl", description: "Wählen Sie aus unseren Premium-Filamenten basierend auf Ihren Anwendungsanforderungen - Festigkeit, Flexibilität oder Ästhetik." },
  { number: 3, title: "Präzisionsdruck", description: "Ihr Modell wird Schicht für Schicht mit industrieller Präzision und Qualitätskontrolle gedruckt." },
  { number: 4, title: "Nachbearbeitung", description: "Teile werden gereinigt, Stützstrukturen entfernt und optionale Veredelung für ein professionelles Ergebnis angewendet." },
  { number: 5, title: "Qualitätsprüfung & Versand", description: "Jedes Stück wird vor der sorgfältigen Verpackung und dem Versand zu Ihnen inspiziert." },
]