/** CMS-Defaults für Storefront-Unterseiten (3D, Laser, Kontakt, Support). */

export const PAGE_CONTENT_SITE_TEXT_DEFAULTS = {
  page_3d_hero_badge: "Additive Fertigung",
  page_3d_hero_title_prefix: "Präzisions ",
  page_3d_hero_title_highlight: "3D-Druck",
  page_3d_hero_subtitle:
    "Von der Konzeption zur Kreation - wir bringen Ihre Ideen mit industrietauglichem 3D-Druck zum Leben. Wählen Sie aus Premium-Materialien, die auf Ihre spezifischen Bedürfnisse zugeschnitten sind.",
  page_3d_hero_cta_primary: "Jetzt 3D-Druck konfigurieren",
  page_3d_hero_cta_secondary: "Produkte Entdecken",
  page_3d_materials_heading_prefix: "Unsere ",
  page_3d_materials_heading_highlight: "Materialien",
  page_3d_materials_subtitle:
    "Wählen Sie das passende Filament für Ihr Projekt — Eigenschaften und Farben im Überblick.",
  page_3d_process_heading_prefix: "So ",
  page_3d_process_heading_highlight: "funktioniert's",
  page_3d_process_subtitle: "Vom Upload bis zur Lieferung — transparent und präzise.",
  page_3d_cta_title: "Bereit für Ihren 3D-Druck?",
  page_3d_cta_subtitle:
    "Laden Sie Ihre Datei hoch oder starten Sie den Konfigurator — wir kümmern uns um den Rest.",
  page_3d_cta_button: "Jetzt konfigurieren",

  page_laser_hero_badge: "Präzisions-Lasertechnologie",
  page_laser_hero_title_prefix: "Laser ",
  page_laser_hero_title_highlight: "Gravur & Schnitt",
  page_laser_hero_subtitle:
    "Präzision trifft Kunstfertigkeit. Unsere Lasertechnologie erzeugt atemberaubende Gravuren und präzise Schnitte auf Holz, Acryl, Leder und mehr.",
  page_laser_hero_cta_primary: "Jetzt Gravur gestalten",
  page_laser_hero_cta_secondary: "Produkte Entdecken",
  page_laser_capabilities_heading_prefix: "Unsere ",
  page_laser_capabilities_heading_highlight: "Möglichkeiten",
  page_laser_capabilities_subtitle:
    "Modernste Lasertechnologie für Gravieren, Schneiden und Markieren verschiedener Materialien.",
  page_laser_materials_heading_prefix: "Geeignete ",
  page_laser_materials_heading_highlight: "Materialien",
  page_laser_materials_subtitle: "Von Naturschiefer bis Acryl — für jedes Motiv das passende Material.",
  page_laser_process_heading_prefix: "Ablauf ",
  page_laser_process_heading_highlight: "Schritt",
  page_laser_process_subtitle: "Vom Design bis zur fertigen Gravur.",
  page_laser_cta_title: "Bereit für Ihre Lasergravur?",
  page_laser_cta_subtitle: "Gestalten Sie Ihr Motiv im Studio oder wählen Sie ein Produkt aus dem Shop.",
  page_laser_cta_button: "Jetzt gestalten",

  page_kontakt_hero_badge: "Kontakt",
  page_kontakt_hero_title_prefix: "Schreib uns ",
  page_kontakt_hero_title_highlight: "eine Nachricht",
  page_kontakt_hero_subtitle:
    "Fragen zu 3D-Druck, Lasergravur oder deiner Bestellung? Wir melden uns so schnell wie möglich.",
  page_kontakt_form_title: "Kontaktformular",
  page_kontakt_sidebar_info_title: "Kontaktinformationen",
  page_kontakt_sidebar_help_title: "Schnelle Hilfe",
  page_kontakt_sidebar_response_title: "Antwortzeit",
  page_kontakt_sidebar_response_body:
    "Wir antworten in der Regel innerhalb von 1–2 Werktagen.",

  page_support_hero_badge: "Community Support",
  page_support_hero_title_prefix: "Unterstütze ",
  page_support_hero_title_highlight: "DripForge",
  page_support_hero_subtitle:
    "Hilf uns, Materialien, Drucker und Laser zu finanzieren — transparent und mit Meilensteinen.",
  page_support_milestones_heading: "Aktuelle Meilensteine",
  page_support_enabled_heading: "Bereits ermöglicht",
  page_support_form_heading: "Beitrag wählen",
  page_support_form_subtitle: "Wähle einen Betrag und unterstütze unser nächstes Ziel.",
  page_support_footer_note:
    "Zahlungen werden sicher über Stripe abgewickelt. Vielen Dank für deine Unterstützung!",
} as const

export const PAGE_CONTENT_SITE_TEXT_SECTIONS = [
  {
    id: "page_3d" as const,
    label: "Seite 3D-Druck",
    fields: [
      { key: "page_3d_hero_badge", label: "Hero-Badge" },
      { key: "page_3d_hero_title_prefix", label: "Hero-Titel (Prefix)" },
      { key: "page_3d_hero_title_highlight", label: "Hero-Titel (hervorgehoben)" },
      { key: "page_3d_hero_subtitle", label: "Hero-Untertitel", multiline: true },
      { key: "page_3d_hero_cta_primary", label: "CTA primär", hrefEditable: true },
      { key: "page_3d_hero_cta_secondary", label: "CTA sekundär" },
      { key: "page_3d_materials_heading_prefix", label: "Materialien Prefix" },
      { key: "page_3d_materials_heading_highlight", label: "Materialien Highlight" },
      { key: "page_3d_materials_subtitle", label: "Materialien Untertitel", multiline: true },
      { key: "page_3d_process_heading_prefix", label: "Prozess Prefix" },
      { key: "page_3d_process_heading_highlight", label: "Prozess Highlight" },
      { key: "page_3d_process_subtitle", label: "Prozess Untertitel", multiline: true },
      { key: "page_3d_cta_title", label: "Abschluss-Titel" },
      { key: "page_3d_cta_subtitle", label: "Abschluss-Text", multiline: true },
      { key: "page_3d_cta_button", label: "Abschluss-Button", hrefEditable: true },
    ],
  },
  {
    id: "page_laser" as const,
    label: "Seite Laser",
    fields: [
      { key: "page_laser_hero_badge", label: "Hero-Badge" },
      { key: "page_laser_hero_title_prefix", label: "Hero-Titel (Prefix)" },
      { key: "page_laser_hero_title_highlight", label: "Hero-Titel (hervorgehoben)" },
      { key: "page_laser_hero_subtitle", label: "Hero-Untertitel", multiline: true },
      { key: "page_laser_hero_cta_primary", label: "CTA primär", hrefEditable: true },
      { key: "page_laser_hero_cta_secondary", label: "CTA sekundär" },
      { key: "page_laser_capabilities_heading_prefix", label: "Möglichkeiten Prefix" },
      { key: "page_laser_capabilities_heading_highlight", label: "Möglichkeiten Highlight" },
      { key: "page_laser_capabilities_subtitle", label: "Möglichkeiten Untertitel", multiline: true },
      { key: "page_laser_materials_heading_prefix", label: "Materialien Prefix" },
      { key: "page_laser_materials_heading_highlight", label: "Materialien Highlight" },
      { key: "page_laser_materials_subtitle", label: "Materialien Untertitel", multiline: true },
      { key: "page_laser_process_heading_prefix", label: "Ablauf Prefix" },
      { key: "page_laser_process_heading_highlight", label: "Ablauf Highlight" },
      { key: "page_laser_process_subtitle", label: "Ablauf Untertitel", multiline: true },
      { key: "page_laser_cta_title", label: "Abschluss-Titel" },
      { key: "page_laser_cta_subtitle", label: "Abschluss-Text", multiline: true },
      { key: "page_laser_cta_button", label: "Abschluss-Button", hrefEditable: true },
    ],
  },
  {
    id: "page_kontakt" as const,
    label: "Seite Kontakt",
    fields: [
      { key: "page_kontakt_hero_badge", label: "Hero-Badge" },
      { key: "page_kontakt_hero_title_prefix", label: "Hero-Titel (Prefix)" },
      { key: "page_kontakt_hero_title_highlight", label: "Hero-Titel (hervorgehoben)" },
      { key: "page_kontakt_hero_subtitle", label: "Hero-Untertitel", multiline: true },
      { key: "page_kontakt_form_title", label: "Formular-Titel" },
      { key: "page_kontakt_sidebar_info_title", label: "Sidebar Kontakt" },
      { key: "page_kontakt_sidebar_help_title", label: "Sidebar Hilfe" },
      { key: "page_kontakt_sidebar_response_title", label: "Antwortzeit Titel" },
      { key: "page_kontakt_sidebar_response_body", label: "Antwortzeit Text", multiline: true },
    ],
  },
  {
    id: "page_support" as const,
    label: "Seite Support",
    fields: [
      { key: "page_support_hero_badge", label: "Hero-Badge" },
      { key: "page_support_hero_title_prefix", label: "Hero-Titel (Prefix)" },
      { key: "page_support_hero_title_highlight", label: "Hero-Titel (hervorgehoben)" },
      { key: "page_support_hero_subtitle", label: "Hero-Untertitel", multiline: true },
      { key: "page_support_milestones_heading", label: "Meilensteine Titel" },
      { key: "page_support_enabled_heading", label: "Bereits ermöglicht Titel" },
      { key: "page_support_form_heading", label: "Formular Titel" },
      { key: "page_support_form_subtitle", label: "Formular Untertitel", multiline: true },
      { key: "page_support_footer_note", label: "Fussnote", multiline: true },
    ],
  },
] as const
